name: CI

on:
  push:
    branches-ignore:
      - "main"
      - "dependabot*"
      - "dependabot/**"

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
