name: QA

on:
  workflow_call:

jobs:
  precommit:
    name: Pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - run: uv sync --locked

      - run: make run_precommit

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - run: uv sync --locked

      - run: make test-unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - run: uv sync --locked

      - run: make test-integration

  pgbouncer-tests:
    name: PgBouncer integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: true

      - run: uv sync --locked

      - run: make test-integration-pgbouncer
